name: esp_provisioning_example
description: Demonstrates how to use the esp_provisioning plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  esp_provisioning:
    path: ../
  flutter_bloc: ^8.1.3
  logger: ^2.0.2+1
  permission_handler: ^11.3.0
  equatable: ^2.0.5
  rxdart: ^0.27.7
  flutter_spinkit: ^5.2.0
  location: ^5.0.3
  cupertino_icons: ^1.0.6
  flutter_blue_plus: ^1.14.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true