name: esp_provisioning
description: Espressif Provisioning library
version: 1.0.0+6
homepage: https://github.com/sunshine-tech/esp_provisioning.git
author: Tuan PM <tuanpm@live.com>

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^3.1.0
  cryptography: ^2.7.0
  collection: ^1.17.2
  flutter_blue_plus: ^1.14.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.tuanpm.esp_provisioning
        pluginClass: EspProvisioningPlugin
      ios:
        pluginClass: EspProvisioningPlugin
